name: Build & Deploy

on: [push, pull_request]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-11
          DEPLOY_PATH: pingviewer-Release.dmg
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.1'
        target: 'desktop'
        modules: qtcharts

    - name: Install jinja2
      run: |
        pip install --user --upgrade pip;
        pip install --user jinja2;

    - name: Build Mac
      if: runner.os == 'macOS'
      run: |
        ./tools/compile.sh
        mv /tmp/ping* .

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pingviewer-${{ matrix.os }}
        path: ${{ matrix.DEPLOY_PATH }}

    - name: Upload continuous to release
      uses: svenstaro/upload-release-action@v2
      if: ${{ github.event_name != 'pull_request' }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.DEPLOY_PATH }}
        tag: continuous
        overwrite: true
        prerelease: true

    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.DEPLOY_PATH }}
        tag: ${{ github.ref }}
        overwrite: true
        prerelease: true
